import { SEDAN, SUV, CROSSOVER, HATCH } from '@/lib/media';

// MOTOR Pakistan — vehicle inventory data.
// All listings are sample/demo data for reference.
export const SEED_VEHICLES = [
  {
    slug: 'toyota-corolla-altis-grande-2026',
    make: 'Toyota',
    model: 'Corolla Altis Grande X 1.8 CVT',
    year: 2025,
    price: 6999000,
    priceLabel: '',
    monthlyEstimate: 134000,
    mileage: 18500,
    powertrain: 'Petrol',
    availabilityStatus: 'Dealer Stock',
    transmission: 'CVT Automatic with 7-Speed Sport Mode',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    engineCapacity: '1.8L Dual VVT-i (138 hp)',
    driveType: 'FWD',
    condition: 'Certified Pre-Owned',
    exteriorColor: 'Super White',
    interiorColor: 'Beige & Black',
    doors: 4,
    seats: 5,
    location: 'Main Boulevard, Gulberg III, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: true,
    isNewArrival: false,
    isGreatValue: true,
    rentalDailyRate: 11000,
    rentalWeeklyRate: 70000,
    rentalDeposit: 35000,
    rentalCategory: 'Sedan',
    batteryCapacity: null,
    electricRange: null,
    combinedRange: null,
    motorPower: null,
    torque: '173 Nm',
    chargingType: null,
    acCharging: null,
    dcFastCharging: null,
    v2l: false,
    batteryWarranty: null,
    vehicleWarranty: 'Inspection report available',
    mainImage: SEDAN.corolla,
    gallery: [SEDAN.corolla],
    features: ['Sunroof', 'Paddle Shifters', 'Cruise Control', 'Reverse Camera', 'Push Button Start', 'Vehicle Stability Control', 'Leather Upholstery', '9-inch Infotainment', 'Apple CarPlay & Android Auto', 'Dual SRS Airbags'],
    description: '2025 Toyota Corolla Altis Grande X 1.8 with 18,500 km on the clock. Single-owner driven in Lahore with a documented service history. Our multi-point inspection covers engine compression, suspension, paint-meter scans and on-ramp test driving. Prices reviewed regularly.'
  },
  {
    slug: 'honda-civic-rs-turbo-2026',
    make: 'Honda',
    model: 'Civic RS 1.5 Turbo LL-CVT',
    year: 2025,
    price: 9599000,
    priceLabel: '',
    monthlyEstimate: 182000,
    mileage: 12400,
    powertrain: 'Petrol',
    availabilityStatus: 'Dealer Stock',
    transmission: 'CVT Automatic with Paddle Shifters',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    engineCapacity: '1.5L VTEC Turbo (176 hp / 220 Nm)',
    driveType: 'FWD',
    condition: 'Certified Pre-Owned',
    exteriorColor: 'Meteoroid Gray Metallic',
    interiorColor: 'Black with Red Stitching',
    doors: 4,
    seats: 5,
    location: 'Block 4, Clifton & DHA Phase 6, Karachi',
    status: 'Available',
    isFeatured: true,
    isRental: false,
    isNewArrival: false,
    isGreatValue: false,
    rentalDailyRate: null,
    rentalWeeklyRate: null,
    rentalDeposit: null,
    rentalCategory: 'Executive',
    batteryCapacity: null,
    electricRange: null,
    combinedRange: null,
    motorPower: null,
    torque: '220 Nm',
    chargingType: null,
    acCharging: null,
    dcFastCharging: null,
    v2l: false,
    batteryWarranty: null,
    vehicleWarranty: 'Inspection report available',
    mainImage: SEDAN.civic,
    gallery: [SEDAN.civic],
    features: ['Honda Sensing ADAS', 'Adaptive Cruise Control', 'Collision Mitigation Braking', 'Lane Keeping Assist', 'Sunroof', 'Wireless Apple CarPlay', 'Digital Instrument Cluster', 'Sport Dual Exhaust'],
    description: '2025 Honda Civic RS Turbo available at our Karachi hub. 12,400 km, complete Honda warranty-service history, no panel repairs recorded. Honda Sensing active safety suite included. Prices reviewed regularly.'
  },
  {
    slug: 'toyota-yaris-ativ-x-2026',
    make: 'Toyota',
    model: 'Yaris ATIV X 1.5 CVT',
    year: 2024,
    price: 4999000,
    priceLabel: '',
    monthlyEstimate: 96000,
    mileage: 21000,
    powertrain: 'Petrol',
    availabilityStatus: 'Dealer Stock',
    transmission: 'CVT Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    engineCapacity: '1.5L Dual VVT-i (106 hp)',
    driveType: 'FWD',
    condition: 'Certified Pre-Owned',
    exteriorColor: 'Silver Metallic',
    interiorColor: 'Black & Ivory',
    doors: 4,
    seats: 5,
    location: 'Expo Centre Road, Johar Town, Lahore',
    status: 'Available',
    isFeatured: false,
    isRental: true,
    isNewArrival: false,
    isGreatValue: true,
    rentalDailyRate: 8500,
    rentalWeeklyRate: 54000,
    rentalDeposit: 25000,
    rentalCategory: 'Economy',
    batteryCapacity: null,
    electricRange: null,
    combinedRange: null,
    motorPower: null,
    torque: null,
    chargingType: null,
    acCharging: null,
    dcFastCharging: null,
    v2l: false,
    batteryWarranty: null,
    vehicleWarranty: 'Inspection report available',
    mainImage: SEDAN.yaris,
    gallery: [SEDAN.yaris],
    features: ['Smart Keyless Entry', 'Push Start', 'Automatic Climate Control', 'Steering Mounted Controls', 'Reverse Camera', 'Hill Start Assist', 'High Fuel Mileage (16+ km/l)'],
    description: '2024 Toyota Yaris ATIV X with 21,000 km, based at our Johar Town branch. Efficient daily commuter with strong city fuel economy. Prices reviewed regularly.'
  },
  {
    slug: 'kia-sportage-awd-2026',
    make: 'KIA',
    model: 'Sportage AWD 2.0 Automatic',
    year: 2026,
    price: 8499000,
    priceLabel: 'Ex-Factory',
    monthlyEstimate: 162000,
    mileage: 150,
    powertrain: 'Petrol',
    availabilityStatus: 'New Arrival',
    transmission: '6-Speed Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    engineCapacity: '2.0L Nu MPI (155 hp)',
    driveType: 'AWD',
    condition: 'Brand New',
    exteriorColor: 'Panthera Metal',
    interiorColor: 'Grey & Black Leather',
    doors: 5,
    seats: 5,
    location: 'Blue Area & Sector F-7, Islamabad',
    status: 'Available',
    isFeatured: true,
    isRental: false,
    isNewArrival: true,
    isGreatValue: false,
    rentalDailyRate: null,
    rentalWeeklyRate: null,
    rentalDeposit: null,
    rentalCategory: 'SUV',
    batteryCapacity: null,
    electricRange: null,
    combinedRange: null,
    motorPower: null,
    torque: null,
    chargingType: null,
    acCharging: null,
    dcFastCharging: null,
    v2l: false,
    batteryWarranty: null,
    vehicleWarranty: 'Manufacturer warranty (as per dealer)',
    mainImage: SUV.sportage,
    gallery: [SUV.sportage],
    features: ['Panoramic Sunroof', 'All-Wheel Drive Lock', 'Wireless Smartphone Charger', 'Electronic Parking Brake with Auto Hold', 'Bi-Xenon Projection Headlamps', 'Smart Power Tailgate', 'Cruise Control', 'Rain Sensing Wipers'],
    description: 'New-arrival 2026 KIA Sportage AWD at our Islamabad hub. Ex-factory indicative pricing shown. Booking and delivery timelines depend on dealer allocation — contact our team for the latest schedule.'
  },
  {
    slug: 'toyota-fortuner-legender-2026',
    make: 'Toyota',
    model: 'Fortuner Legender 2.8D 4x4',
    year: 2025,
    price: 19999000,
    priceLabel: '',
    monthlyEstimate: 378000,
    mileage: 28000,
    powertrain: 'Diesel',
    availabilityStatus: 'Dealer Stock',
    transmission: '6-Speed Sequential Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    engineCapacity: '2.8L 1GD-FTV Turbo Diesel (201 hp / 500 Nm)',
    driveType: '4WD',
    condition: 'Certified Pre-Owned',
    exteriorColor: 'Super White Dual Tone',
    interiorColor: 'Maroon & Black Leather',
    doors: 5,
    seats: 7,
    location: 'Main Boulevard, Gulberg III, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: true,
    isNewArrival: false,
    isGreatValue: false,
    rentalDailyRate: 26000,
    rentalWeeklyRate: 165000,
    rentalDeposit: 75000,
    rentalCategory: 'SUV',
    batteryCapacity: null,
    electricRange: null,
    combinedRange: null,
    motorPower: null,
    torque: '500 Nm',
    chargingType: null,
    acCharging: null,
    dcFastCharging: null,
    v2l: false,
    batteryWarranty: null,
    vehicleWarranty: 'Inspection report available',
    mainImage: SUV.fortuner,
    gallery: [SUV.fortuner],
    features: ['4x4 Differential Lock', 'Power Backdoor with Kick Sensor', 'Ventilated Front Seats', '360 Panoramic View Camera', 'Paddle Shifters', 'Drive Modes', '7 Full Leather Seats', 'Dual Zone Climate Control', '7 SRS Airbags'],
    description: '2025 Toyota Fortuner Legender 2.8D 4x4 with 28,000 km. Used by a single corporate owner between Lahore and Islamabad motorway routes. Full underbody and 4x4 driveline inspection completed. Prices reviewed regularly.'
  },
  {
    slug: 'toyota-corolla-cross-hev-2026',
    make: 'Toyota',
    model: 'Corolla Cross 1.8 HEV Premium',
    year: 2025,
    price: 9299000,
    priceLabel: 'Starting From',
    monthlyEstimate: 177000,
    mileage: 600,
    powertrain: 'Hybrid',
    availabilityStatus: 'Available in Pakistan',
    transmission: 'E-CVT Automatic',
    fuelType: 'Hybrid',
    bodyType: 'Crossover',
    engineCapacity: '1.8L 2ZR-FXE + Electric Motor (168 hp combined)',
    driveType: 'FWD',
    condition: 'Brand New',
    exteriorColor: 'Celestite Gray Metallic',
    interiorColor: 'Terra Rossa Leather',
    doors: 5,
    seats: 5,
    location: 'Main Boulevard, Gulberg III, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: true,
    isNewArrival: true,
    isGreatValue: true,
    rentalDailyRate: 16500,
    rentalWeeklyRate: 105000,
    rentalDeposit: 45000,
    rentalCategory: 'SUV',
    batteryCapacity: '1.3 kWh NiMH Traction Battery',
    electricRange: 'Self-charging EV mode in traffic',
    combinedRange: '880 km on a 36L tank (20+ km/l)',
    motorPower: '71 hp Permanent Magnet Motor',
    torque: '163 Nm (motor)',
    chargingType: 'Self-Charging (regenerative braking)',
    acCharging: 'No plug required',
    dcFastCharging: 'N/A',
    v2l: false,
    batteryWarranty: '8 Years / 160,000 km (hybrid battery)',
    vehicleWarranty: 'Manufacturer warranty (as per dealer)',
    mainImage: CROSSOVER.corollaCross,
    gallery: [CROSSOVER.corollaCross],
    features: ['Toyota Hybrid Synergy Drive', 'EV Mode Selector', 'Dual-Zone Auto Climate', 'Power Tailgate', 'Blind Spot Monitor', 'Rear Cross Traffic Alert', '7-inch Digital Instrument Cluster', '9 SRS Airbags'],
    description: 'Self-charging hybrid crossover. No plug required — the petrol engine and regenerative braking keep the battery topped up automatically. Real-world Lahore city fuel economy regularly exceeds 20 km/l in stop-and-go traffic.'
  },
  {
    slug: 'mg-hs-phev-2026',
    make: 'MG',
    model: 'HS Super Hybrid PHEV',
    year: 2025,
    price: 10199000,
    priceLabel: 'Starting From',
    monthlyEstimate: 194000,
    mileage: 400,
    powertrain: 'PHEV',
    availabilityStatus: 'Available in Pakistan',
    transmission: '10-Speed EDU II Hybrid Transmission',
    fuelType: 'Plug-in Hybrid',
    bodyType: 'SUV',
    engineCapacity: '1.5L Turbo + Electric Motor (280 hp / 480 Nm combined)',
    driveType: 'FWD',
    condition: 'Brand New',
    exteriorColor: 'Arctic Pearl White',
    interiorColor: 'Bader Black Leather',
    doors: 5,
    seats: 5,
    location: 'Main Boulevard, Gulberg III, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: false,
    isNewArrival: true,
    isGreatValue: false,
    rentalDailyRate: null,
    rentalWeeklyRate: null,
    rentalDeposit: null,
    rentalCategory: 'SUV',
    batteryCapacity: '16.6 kWh Lithium-ion',
    electricRange: '52 km (pure electric)',
    combinedRange: '1,000+ km combined',
    motorPower: '122 hp (90 kW) electric motor',
    torque: '480 Nm combined',
    chargingType: 'Type 2 AC wallbox / 3-pin portable charger',
    acCharging: '3.7 kW (approx 4.5 hours full charge)',
    dcFastCharging: 'N/A',
    v2l: false,
    batteryWarranty: '8 Years / 150,000 km (battery)',
    vehicleWarranty: '5 Years / 150,000 km',
    mainImage: CROSSOVER.mgHs,
    gallery: [CROSSOVER.mgHs],
    features: ['MG Pilot ADAS Level 2', 'Panoramic Stargazer Sunroof', '10.1-inch Touchscreen with Navigation', 'Adaptive Cruise Control', 'Lane Keep Assist', 'Regenerative Braking (3 levels)'],
    description: 'Plug-in hybrid SUV. Up to 52 km of pure electric driving for daily commutes in Lahore, with the turbocharged engine taking over for long-distance motorway trips — over 1,000 km combined range.'
  },
  {
    slug: 'changan-lumin-ev-2026',
    make: 'Changan',
    model: 'Lumin 205km EV',
    year: 2025,
    price: 4849000,
    priceLabel: 'Ex-Factory',
    monthlyEstimate: 94000,
    mileage: 200,
    powertrain: 'EV',
    availabilityStatus: 'Available in Pakistan',
    transmission: 'Single-Speed Electric Drive',
    fuelType: 'Electric',
    bodyType: 'Hatchback',
    engineCapacity: 'Electric Motor (41 hp / 30 kW)',
    driveType: 'FWD',
    condition: 'Brand New',
    exteriorColor: 'Sakura Green Dual-Tone',
    interiorColor: 'Grey & Teal',
    doors: 3,
    seats: 4,
    location: 'Expo Centre Road, Johar Town, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: true,
    isNewArrival: true,
    isGreatValue: true,
    rentalDailyRate: 8000,
    rentalWeeklyRate: 50000,
    rentalDeposit: 25000,
    rentalCategory: 'Economy',
    batteryCapacity: '17.65 kWh LFP battery',
    electricRange: '205 km (city)',
    combinedRange: '205 km',
    motorPower: '41 hp (30 kW)',
    torque: '88 Nm',
    chargingType: 'Type 2 AC / standard 220V household socket',
    acCharging: '3.3 kW (0-100% in approx 5.8 hours)',
    dcFastCharging: 'N/A (city commuter)',
    v2l: false,
    batteryWarranty: '8 Years / 120,000 km (battery)',
    vehicleWarranty: '3 Years / 100,000 km',
    mainImage: HATCH.lumin,
    gallery: [HATCH.lumin],
    features: ['10.25-inch Touchscreen', 'Hidden Flush Door Handles', 'Dual Airbags & ABS', 'Keyless Entry & Push Start', 'Ultra-low running cost (approx PKR 400 per 100 km)'],
    description: 'Compact pure-electric city hatchback. Charges overnight on a standard 220V household socket. Ideal for daily commutes in Gulberg, DHA and Johar Town at a fraction of petrol running costs.'
  },
  {
    slug: 'deepal-s07-reev-2026',
    make: 'Deepal',
    model: 'S07 REEV (Range Extended EV)',
    year: 2025,
    price: 14200000,
    priceLabel: 'Ex-Factory',
    monthlyEstimate: 265000,
    mileage: 900,
    powertrain: 'REEV',
    availabilityStatus: 'New Arrival',
    transmission: 'Single-Speed Electric Direct Drive',
    fuelType: 'Range Extended EV',
    bodyType: 'SUV',
    engineCapacity: 'Electric Motor (238 hp) + 1.5L Range Extender Generator',
    driveType: 'RWD',
    condition: 'Brand New',
    exteriorColor: 'Moonlight Grey Metallic',
    interiorColor: 'Sunset Orange Nappa Leather',
    doors: 5,
    seats: 5,
    location: 'Sector C Commercial, DHA Phase 5, Lahore',
    status: 'Available',
    isFeatured: true,
    isRental: true,
    isNewArrival: true,
    isGreatValue: false,
    rentalDailyRate: 24000,
    rentalWeeklyRate: 150000,
    rentalDeposit: 70000,
    rentalCategory: 'Executive',
    batteryCapacity: '31.7 kWh battery',
    electricRange: '200 km (pure electric)',
    combinedRange: '1,120 km total (with range extender)',
    motorPower: '238 hp (175 kW)',
    torque: '320 Nm',
    chargingType: 'Type 2 AC & CCS2 DC fast charging',
    acCharging: '7 kW (approx 4.5 hours)',
    dcFastCharging: '50 kW (30-80% in approx 30 mins)',
    v2l: true,
    batteryWarranty: '8 Years / 160,000 km (battery)',
    vehicleWarranty: '5 Years / 150,000 km',
    mainImage: CROSSOVER.deepalS07,
    gallery: [CROSSOVER.deepalS07],
    features: ['Electric drive with a range-extending petrol engine', '15.6-inch Rotating Display', 'AR Head-Up Display', 'Frameless Doors', 'V2L 3.3 kW power output', 'Level 2.5 assisted driving'],
    description: 'Range Extended EV: the wheels are driven 100% by the electric motor. The petrol engine only charges the battery on long journeys — 200 km pure electric range, 1,120 km total. No charging queues on the motorway.'
  }
];

export const SEED_OFFERS = [
  {
    title: 'EV Home Charger Installation Package',
    slug: 'ev-home-charger-bundle',
    badge: 'With EV Bookings',
    description: 'Book an EV or PHEV through the platform and request a Level-2 AC home charging consultation for Lahore, Islamabad or Karachi residences.',
    discountDetails: 'Installation support (demo offer)',
    validUntil: 'Limited-time offer',
    imageUrl: HATCH.lumin,
    category: 'Sales',
    isActive: true,
    ctaText: 'Explore EV Cars',
    ctaLink: '/electric-cars-pakistan'
  },
  {
    title: 'Weekend SUV Rental Package',
    slug: 'weekend-escape-suv-package',
    badge: '15% Off Rentals',
    description: 'Rent a Fortuner, Corolla Cross or Yaris from Friday to Monday with free additional driver registration on weekend bookings.',
    discountDetails: 'Flat 15% off 3-day weekend bookings',
    validUntil: 'Limited-time offer',
    imageUrl: SUV.fortuner,
    category: 'Rental',
    isActive: true,
    ctaText: 'Book Weekend SUV',
    ctaLink: '/rent'
  },
  {
    title: 'Trade-In Evaluation Bonus',
    slug: 'certified-trade-in-bonus',
    badge: 'Trade-In Value Check',
    description: 'Trade in your existing vehicle against any listing. Submit your car details and receive an estimated evaluation range from the team.',
    discountDetails: 'Illustrative estimate only',
    validUntil: 'Limited-time offer',
    imageUrl: SEDAN.corolla,
    category: 'Sales',
    isActive: true,
    ctaText: 'Value My Car',
    ctaLink: '/sell'
  }
];

export const SEED_REVIEWS = [
  {
    customerName: 'Ahmed Raza',
    customerRole: 'Business Owner',
    location: 'Gulberg, Lahore',
    vehicle: 'Toyota Corolla Altis Grande X',
    rating: 5,
    reviewText: 'Found the exact Corolla variant I was looking for, inspected it with my own mechanic, and the paperwork was handled without any surprises. The whole process felt transparent from start to finish.',
    date: 'March 2026',
    isVerified: true
  },
  {
    customerName: 'Sana Khalid',
    customerRole: 'IT Consultant',
    location: 'DHA Phase 6, Lahore',
    vehicle: 'Toyota Corolla Cross HEV',
    rating: 5,
    reviewText: 'Booked a Corolla Cross rental for a family trip and everything was ready on time, clean and with a full tank. The WhatsApp team answered all my questions before the booking.',
    date: 'February 2026',
    isVerified: true
  },
  {
    customerName: 'Imran Malik',
    customerRole: 'Sales Director',
    location: 'F-7, Islamabad',
    vehicle: 'KIA Sportage AWD',
    rating: 5,
    reviewText: 'Compared three SUVs on the platform, shortlisted the Sportage, and reserved it through the Islamabad hub. Delivery and registration guidance were professional throughout.',
    date: 'January 2026',
    isVerified: true
  },
  {
    customerName: 'Bilal Ahmed',
    customerRole: 'Doctor',
    location: 'Johar Town, Lahore',
    vehicle: 'Deepal S07 REEV',
    rating: 5,
    reviewText: 'The team explained the REEV concept properly — electric drive with a petrol generator for long trips. Test drove it on Ring Road and booked it the same afternoon.',
    date: 'January 2026',
    isVerified: true
  }
];

export const SEED_LEADS = [
  {
    leadType: 'Financing',
    customerName: 'Usman Tariq',
    customerEmail: 'usman.tariq@example.com',
    customerPhone: '+92 300 8472910',
    vehicleInterested: 'Toyota Corolla Cross HEV 2025',
    vehicleId: 6,
    message: 'Interested in 3-year financing option with 30% down payment.',
    source: 'Website',
    status: 'Negotiation',
    estimatedValue: 9299000,
    assignedSalesperson: 'Hamza Farooq',
    nextFollowUp: 'Tomorrow, 11:00 AM'
  },
  {
    leadType: 'Sell Car',
    customerName: 'Fatima Noor',
    customerEmail: 'fatima.noor@example.com',
    customerPhone: '+92 321 4455882',
    vehicleInterested: '2021 Toyota Corolla GLi 1.3',
    vehicleId: null,
    message: 'Want to sell my 2021 Corolla GLi (44,000 km, Lahore registered).',
    source: 'WhatsApp',
    status: 'Contacted',
    estimatedValue: 4200000,
    assignedSalesperson: 'Rehan Malik',
    nextFollowUp: 'Today, 4:30 PM'
  },
  {
    leadType: 'Rental',
    customerName: 'Murtaza Kazmi',
    customerEmail: 'murtaza.kazmi@example.com',
    customerPhone: '+92 333 5192837',
    vehicleInterested: 'Toyota Fortuner Legender 2.8D',
    vehicleId: 5,
    message: 'Need a Fortuner for a corporate delegation in Lahore for 4 days.',
    source: 'Website',
    status: 'Qualified',
    estimatedValue: 104000,
    assignedSalesperson: 'Sarmad Javed',
    nextFollowUp: 'Tomorrow, 2:00 PM'
  }
];

export const SEED_BOOKINGS = [
  {
    bookingReference: 'DH-RNT-91042',
    vehicleId: 1,
    vehicleName: 'Toyota Corolla Altis Grande X 1.8 CVT',
    customerName: 'Haris Mehmood',
    customerEmail: 'haris.mehmood@example.com',
    customerPhone: '+92 300 4567890',
    customerCnicPlaceholder: 'Verified at pickup',
    pickupLocation: 'Main Boulevard, Gulberg III, Lahore',
    dropoffLocation: 'Allama Iqbal International Airport (LHE)',
    pickupDate: '2026-04-28',
    pickupTime: '10:00 AM',
    returnDate: '2026-05-01',
    returnTime: '06:00 PM',
    rentalDays: 3,
    dailyRate: 11000,
    extras: [{ name: 'Comprehensive Cover', price: 3000 }],
    extrasTotal: 3000,
    securityDeposit: 35000,
    totalAmount: 36000,
    status: 'Approved',
    notes: 'Airport drop-off arranged.'
  },
  {
    bookingReference: 'DH-RNT-88412',
    vehicleId: 6,
    vehicleName: 'Toyota Corolla Cross 1.8 HEV Premium',
    customerName: 'Naveed Qureshi',
    customerEmail: 'naveed.qureshi@example.com',
    customerPhone: '+92 321 9988776',
    customerCnicPlaceholder: 'Verified at pickup',
    pickupLocation: 'DHA Phase 5 Commercial, Lahore',
    dropoffLocation: 'DHA Phase 5 Commercial, Lahore',
    pickupDate: '2026-04-26',
    pickupTime: '09:00 AM',
    returnDate: '2026-04-29',
    returnTime: '08:00 PM',
    rentalDays: 3,
    dailyRate: 16500,
    extras: [{ name: 'Additional Driver', price: 2500 }],
    extrasTotal: 2500,
    securityDeposit: 45000,
    totalAmount: 52000,
    status: 'Active',
    notes: 'Customer collected vehicle from DHA branch.'
  }
];

export const SEED_TEST_DRIVES = [
  {
    reference: 'DH-TD-7019',
    vehicleId: 9,
    vehicleName: 'Deepal S07 REEV',
    customerName: 'Waleed Zafar',
    customerEmail: 'waleed.zafar@example.com',
    customerPhone: '+92 301 2345678',
    preferredDate: '2026-04-29',
    preferredTime: '03:00 PM',
    location: 'Main Boulevard, Gulberg III, Lahore',
    status: 'Approved',
    salesperson: 'Hamza Farooq',
    notes: 'Customer wants to experience the range extender transition.'
  },
  {
    reference: 'DH-TD-8120',
    vehicleId: 7,
    vehicleName: 'MG HS Super Hybrid PHEV',
    customerName: 'Malik Jahangir',
    customerEmail: 'jahangir.malik@example.com',
    customerPhone: '+92 334 8877665',
    preferredDate: '2026-04-30',
    preferredTime: '11:30 AM',
    location: 'Sector C Commercial, DHA Phase 5, Lahore',
    status: 'Pending',
    salesperson: 'Rehan Malik',
    notes: 'Prefers an extended test drive along Ring Road.'
  }
];
